### ISSUE TITLE
Repeater column head scrolls inside modal on mobile devices

### ISSUE THREAD

**Issue by cristalembalagens** [ExactTarget/fuelux#1015]
I found a problem when using repeater inside a bootstrap modal, when i scroll the items, the column head scrolls too when using mobile devices like smartphones or tablets. When using on a computer, it seems just to lose its rendering. On mobile devices it renders the head again when changing orientation or when selecting a row. Outside the modal it works perfectly.

http://jsfiddle.net/4cLn5jf4/3/

**Comment by kevinparkerson** [comment]
Hi @cristalembalagens. Thanks for pointing this issue out. While I haven't investigated the mobile devices yet, I noticed an issue with the headers being wrong in the modal even on a computer via your example. The reason for this is due to when the repeater runs it's "resize" code. In your example, the repeater is instantiated prior to the modal being opened, thus the sizes are based off of something different than when it is actually displayed. To correct this, a call to `$('#myRepeater').repeater('resize');` after the modal is opened is needed. I've updated your fiddle here to demonstrate:

http://jsfiddle.net/4cLn5jf4/4/

I'm not yet sure if this would address the mobile issues as well, will have to look into this later on.

**Comment by cristalembalagens** [comment]
Hi @kevinparkerson i really works perfectly in my computer now, but it still has the issue with mobile devices. I attached an image of my phone with your fiddle the give you an example of whats happening when I scroll.

Thank you.

![img_3195](https://cloud.githubusercontent.com/assets/10708891/5999490/6a30e698-aab9-11e4-9770-18e9b927b05c.PNG)

**Comment by cristalembalagens** [comment]
I've tested now on an android device with chrome browser, the issue does not happen, it's happening only on iOS devices, with any browser.

**Comment by kevinparkerson** [comment]
Appreciate the details on this @cristalembalagens, as it will help us zero down on the bug a ton! We have a big repeater change in the works at the moment to address a different issue. This problem will probably be next on our list, but we aren't able to work on it just quite yet. Definitely soon though!

**Comment by futuremint** [comment]
We would accept a pull request to fix this, however we are not going to work on this ourselves at this time.
