### ISSUE TITLE
remove multiple `data-initialize=radio` in docs

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#1048]
https://github.com/ExactTarget/fuelux/blob/511f3c471d635d7d9262b898f4652fcff882da90/_includes/js/radio.html#L110

**Comment by mbeard** [comment]
Is the problem here also that each label isn't wrapped with the appropriate `<div class="radio">` container too.

**Comment by interactivellama** [comment]
Yeah, that, too.

**Comment by cormacmccarthy** [comment]
wait... these are inline radio boxes. Why would we wrap them in divs?

**Comment by cormacmccarthy** [comment]
And, actually, I'm not sure why I ever even agreed to, and then added the wrapper div in the first place. It messes things up.

Here's the new (seems to me wrong) way (notice the spacing gets messed up and that all 3 radios appear disabled):
http://jsfiddle.net/cmcculloh/44gf7wb1/

Here's the old (working) way (no spacing or disabled problems):
http://jsfiddle.net/cmcculloh/ropqbn30/

**Comment by cormacmccarthy** [comment]
So, I actually propose we revert my original commit. I sort of just assumed @jmgekeler knew what the markup was supposed to be, but, now I'm wondering why he thought it was wrong in issue #1017 ? 

@interactivellama mentioned something about destroy not working properly because it looks for the `.radio` class. If that's the case, we have some deeper issues here.

**Comment by cormacmccarthy** [comment]
destroy issue is addressed by #1058
