### ISSUE TITLE
radio button docs should encourage usage of `for`

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux#1062]
In the spirit of good markup `for` should be on the `label`s in our examples. We can include an asterisks saying not 100% but encourage.

**Comment by interactivellama** [comment]
Bootstrap uses `for` in their markup. Good addition.

**Comment by mbeard** [comment]
Why is this needed/suggested since these inputs are nested within a label?  It makes sense if the label and input were decoupled, but if the input is nested within a label it's not necessary is it?

Not Needed:
`<label><input type="checkbox"> foo</label>`

Needed:
`<input type="checkbox" id="chk1"><label for="chk1">foo</label>`

**Comment by scott-joe** [comment]
Do we have supported markup that doesn't nest an input within a label?
