### ISSUE TITLE
less/fuelux-no-namespace.less causing watch task problems

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1107]
Slow churning infinite loop initiates while using the `grunt servefast` task. As soon as you make a file change and the watch task kicks off, the face that the no-namespace file deletes itself kicks off the next watch task, rinse, wash, repeat, forever.

**Comment by interactivellama** [comment]
I'm not getting that problem, but `index.html` is broken because the client side LESS compiler is not working. I'm thinking the no namespace enhancement is causing more problems than it's worth.

What about wrapping each files contents individually in `.fuelux {}` would that solve the parent selector issue? @chriscorwin 

I don't mind it not being dry and having `.fuelux {}` at the top of 12 CSS files. I'm little less worried about MCtheme, since that is internally focused.

![screen shot 2015-02-18 at 1 54 36 pm](https://cloud.githubusercontent.com/assets/1290832/6254321/b232b9bc-b775-11e4-935c-6048a28f4118.png)

**Comment by interactivellama** [comment]
Update: I am having watch problems also.

**Comment by interactivellama** [comment]
Ran into this issue today, too. Looks like the source mapping is incorrect.

![screen shot 2015-02-18 at 2 21 32 pm](https://cloud.githubusercontent.com/assets/1290832/6254857/a876e30e-b779-11e4-99fa-ca7a3197fe3d.png)

**Comment by chriscorwin** [comment]
Didn't this get fixed?

The fix I did seems to be in master, anyway.

**Comment by cormacmccarthy** [comment]
From what I can tell, your fixes are in #1115, not master: https://github.com/ExactTarget/fuelux/pull/1115/files#diff-35b4a816e0441e6a375cd925af50752cL347

**Comment by chriscorwin** [comment]
Okay, well, that' in review and should be in master soon.
