### ISSUE TITLE
log utility

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux#1119]
Notes: 
Public utility. Introduce ENV_VAR and FUX_VERSION to library.

`$.fn.fuxLogger.log()`

Options:
* dev vs prod
* show message once
* version restrictions

**Comment by kevinparkerson** [comment]
Perhaps instead of being just a log utility, we make a `core.js` file within the js folder. This would add a `fuelux` object to the jQuery object, which could have a logging utility, information on the version, etc. This would be convenient for things that need to share certain bits of code across fuelux controls, as well as developers looking to quickly see which version of Fuel UX is in their app (although control by control version is also something we should probably have, as Bootstrap now does)

The only drawback to this is that for people using browser globals and control by control inclusion, they'll also have to be aware of the `core.js` file, adding it before any specific controls. AMD / Common users will have no problem with this, since we'd update the other modules to list core as a dependency. Since most browser global users simply add the full fuelux bundle vs individual controls, I think this is a relatively small concern. A little documentation on that caveat should be just fine.

**Comment by swilliamset** [comment]
After umd wrapper removed from src (only on dist) try either 

```
(function ($, FuelLog) {
. . .
})(jQuery, console))
```

or

```
(function ($) {
FuelLog = FuelLog || { log: $.noop };
. . .
})(jQuery))
```

**Comment by swilliamset** [comment]
@chriscorwin to follow up on best approach
