### ISSUE TITLE
refresh specific node in tree

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux#1127]
trigger ajax call to re render children

**Comment by cormacmccarthy** [comment]
So after that create folder dialog successfully submits and creates a folder, i want the folder tree to refresh a specific part of the tree based on the categoryId, I see you can do a $('#folderTree').tree('openFolder', $('#4008')); to open a specific folder. The problem is that I don't see a way to close the folder first, or to force it to make the request again, even when cacheItems is false

**Comment by cormacmccarthy** [comment]
@dkilgore this bud's for you

**Comment by mbeard** [comment]
Just to clarify, the need is for the openFolder method to call the dataSource provider when cacheItems is set to false?

**Comment by dkilgore** [comment]
@mbeard Yes, when cacheItems is set to false openFolder should call the dataSource again. This could be toggled by an option that is passed with the function call.

My use-case is a user creates a new folder from a modal and the parent folder needs to re-open, even if already opened and call the dataSource so that the new folder shows up in the UI.

**Comment by cormacmccarthy** [comment]
hrm... I wonder if we can utilize `populate()` here instead. After all, that's mostly what `openFolder()` actually does.

**Comment by cormacmccarthy** [comment]
`openFolder` works, `populate` does not. redundant `openFolder` calls actually already do re-trigger population...
