### ISSUE TITLE
trigger appropriate events when reaching limits in spinbox

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux#1153]
`minReached.fu.spinbox` `maxReached.fu.spinbox`
https://github.com/ExactTarget/fuelux/blob/master/js/spinbox.js#L220

**Comment by interactivellama** [comment]
This is complex, because the control flow runs through `step` and `change` multiple times due to `focusout` events that fire when focusing and unfocusing on increment buttons. `changed.fu.spinbox` is only fired once, since the multiple comparisons of the same input are the same. This probably accounts for the long-standing bug of a double changed event on focus when first interacting with the control.

The complex flow of spinner may be due in part to it trying to control native issues with `focusout`.

**Comment by cormacmccarthy** [comment]
This should be relatively straight forward at this point. Talk to DBB about event names.
