### ISSUE TITLE
Add checkbox (no-js) to documentation

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#1160]
I'd recommend at the top of the checkbox section (or at the end) and adding a deprecation notice on the "old" checkboxen.

**Comment by chriscorwin** [comment]
I will totally do this.

**Comment by swilliamset** [comment]
documentation should assume both no-js and js solutions will exist

**Comment by interactivellama** [comment]
Bump for documentation.

I just spent about 10 minutes figuring out that I had to have IDs and for attributes on my label for the non-JS checkboxes to work.

**Comment by interactivellama** [comment]
Also, kind of makes me wonder if we should have some kind of JS hack that looks at the previous hidden input and checks it upon clicking the label. I know that I don't want to write a different ID for each checkbox (not saying that I shouldn't, I should.)

**Comment by swilliamset** [comment]
a "no js" solution requires appropriatly built html. for a label and input to work together you need an id attribute and a for attribute `<label for="myInput">Click Me</label><input type="checkbox" id="myInput />`. we should make this clear in the documentation, yes. however adding js would make the solution no longer "no js".

**Comment by chriscorwin** [comment]
`for` and `id` are not strictly required, but in oder to target the proper `input` from a `label`, you need to tell it which one. 

One way to do that is to nest the `input` inside the label. We can't do that here, because they need to be _siblings_ in order for us to style the `label::before` based on the state of the `input` `::checked` attribute.

Therefore: yes, they must all have the `id` and `for` attributes.

I am loathe to go down the path of documenting regular old HTML stuff in the Fuel UX documentation.

How do we decide what to document?

How much of the HTML spec? 

I think our focus should be on _Fuel UX_ things, and not stuff HTML authors _really should know anyway_.

**Comment by chriscorwin** [comment]
After some discussing with @interactivellama, we've arrived at something like this:

> **Note:** When refactoring to use the non-javascript styles, be sure that your `label` elements are pointing to the proper `input` elements by making use of the `for` and `id` attributes. See more information here: <link to HTML5 for developers about this>.
