### ISSUE TITLE
repeater dataSource to support array

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux#1166]

**Comment by kevinparkerson** [comment]
It doesn't make sense to support just an array instead of a function, since the function / callback pattern is a common convention across several fuelux controls with a `dataSource`. Instead, I've made the repeater function even without a dataSource and be a lot more lenient with what's passed back in the callback. @swilliamset thoughts on this decision?

**Comment by swilliamset** [comment]
```If( dataSource.constructor === Array ) {
  // determine length page etc
  // call callback
}```

**Comment by cormacmccarthy** [comment]
We will be addressing this in an upcoming release. Thank you!

**Comment by futuremint** [comment]
This would be a great idea, however we're not going to add this unless its an explicit ask from a scrum team.
