### ISSUE TITLE
Move UMD wrapped controls to dist folder

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#1168]
- Increases clarification of "product" from "source." _Product = dist folder_
- JS files will be global only and "backwards-compatible" [sic] for anyone familiar with Bootstrap. This means it _is_ a breaking change for AMD users of Fuel UX if they are directly using files in the JS folder.
- Reduces "duplicate code."

Should we convert QUnit tests to globals? Otherwise testing will explicitly require a dist build. What are the ramifications of this?

**Comment by cormacmccarthy** [comment]
IMO we should just be testing the _actual product_ that people will be using. There's no reason to not require a dist build to do unit tests, because the unit tests themselves take way longer than a dist build anyways.

**Comment by cormacmccarthy** [comment]
May be able to influence bithound tests: https://www.bithound.io/blog/post/customizing-jshint-on-bithound

**Comment by kevinparkerson** [comment]
We don't want to build dist every time b/c we don't want contributors committing dist files with their PRs, which would be an issue here unless we built, ran tests, then removed the built files (which seems silly). Additionally, we want to encourage people testing via browser and terminal frequently, but having a heavier dist build process might discourage that.

I think we could simply modify our main tests to be browser-global based. Provided our source js files are still encapsulated after removing the UMD wrapper (and @cmcculloh has told me they will be), we can simply include them on the test page and run our tests. We already do this for the browser-global tests, but the change here would be to run full tests on these controls. We would not test via require, but since we have quite a lot of confidence in the UMD wrapper, I'm not sure that is necessary. Of course, we could always make that part of a "release" test if we wanted to.

**Comment by kevinparkerson** [comment]
As part of this change, we should update the UMD wrapper we are using to support Common:

https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js

**Comment by cormacmccarthy** [comment]
Actually Kevin, we already have it built into the grunt task to build, run tests, and remove built files. There's even a grunt task `grunt resetdist` to help out with this.

**Comment by cormacmccarthy** [comment]
Also, afaik, our tests allow you to test either non-built or built. It's based off of URL param and defaults to non-built (I believe). I'll re-confirm this though; if it somehow got changed, I'll put it back (I worked hard on it the first time! ;P )

**Comment by cormacmccarthy** [comment]
We will be addressing this in an upcoming release. Thank you!
