### ISSUE TITLE
CSS only checkbox/radio styling issues

### ISSUE THREAD

**Issue by mbeard** [ExactTarget/fuelux#1180]
1. Checkbox has a pressed state when disabled and should not.  This occurs both for a checkbox that is checked and unchecked
![screenshot 2015-03-17 18 13 32](https://cloud.githubusercontent.com/assets/467352/6698693/5e295288-ccd1-11e4-9c65-4f5d9c6e26e0.png)

2. Can we remove the outline so it is consistent with the js versions

3. Radio hover style is not very crisp
![screenshot 2015-03-17 18 14 24](https://cloud.githubusercontent.com/assets/467352/6698709/7ae3ef14-ccd1-11e4-86f6-b275b7f34a2e.png)

4. Radio unchecked disabled state has a hover style and should not.
![screenshot 2015-03-17 18 15 26](https://cloud.githubusercontent.com/assets/467352/6698718/9cf97fce-ccd1-11e4-849b-a1b62a177820.png)

5. Radio/Checkbox text does not indent properly when wrapped
![screenshot 2015-03-17 18 11 16](https://cloud.githubusercontent.com/assets/467352/6698672/1a1a5ae2-ccd1-11e4-9176-70b934dc87ff.png)

**Comment by chriscorwin** [comment]
@mbeard : What is "properly' for number 5?  The text should align with each other and not the input?

**Comment by chriscorwin** [comment]
I don't see any way to have both of the following without requiring a span around the text: 

(a) a label that styles based on checked state
(b) wrapping like we wish. 


The reason the custom control can wrap like that is that the input is _inside the label_ and the text is in a custom span. 

We have to put the label _next to_ the input or we can't style it based on the `:checked` state, and we can't wrap _only_ the label and not the input since the "input" is actually a pseudo-element _attached to the label_.

Make sense?

I believe that I can have the wrapping be like we want _if_ I introduce a span around the text in the label, but I'll need to poke at it, and I must admit that I find doing so distasteful.

I don't like to require markup like that.  :/

**Comment by mbeard** [comment]
(a) I don't think we need label styles based on checked state.
(b) Indentation should ensure that the text is aligned under itself, not under the checkbox - like [this](https://www.dropbox.com/s/7o3rstxnp7kfpnd/Screenshot%202015-03-19%2012.34.10.png?dl=0).  We should be able to do this through a combination of padding on the container and negative margin on the nested element.

**Comment by chriscorwin** [comment]
> (a) I don't think we need label styles based on checked state.

We do though -- that's how highlight, hover, and checked works: remember, we're not styling the `input` element itself: we are styling a pseudo-element `:before` that is on the `label`.

Without styling the label, there is no custom-styled checkbox, no highlight effect, and no hover effect.

Basically, everything we are doing, iow.

**Comment by interactivellama** [comment]
I think I've found a fix using `box-shadow`.

**Comment by interactivellama** [comment]
Fixed by #1209
