### ISSUE TITLE
require('fuelux/dropdown-autoflip'); not documented for pillbox

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux#1208]
For this example:

http://getfuelux.com/javascript.html#pillbox-examples

we are not noting that dropdown-autoflip is required.

**Comment by interactivellama** [comment]
**For context:**
The default markup uses `<ul class="suggest dropdown-menu" role="menu" data-toggle="dropdown" data-flip="auto"></ul>` for the suggestions drop down.

If you don't define a callback with the `onKeyDown` option. `dropdown-auto-flip` is never called, nor needed. Using AMD `fuelux/dropdown-autoflip` is required though to be defined, because it's been required on line 17 of `pillbox.js`.

**Comment by swilliamset** [comment]
To simplify could auto flip be removed from the base example?
