### ISSUE TITLE
Repeater programmatic interface documentation

### ISSUE THREAD

**Issue by vigna** [ExactTarget/fuelux#1242]
The guidelines on the WIki claim that controls should be accessible programmatically. But we couldn't find any documentation about this for Repeater.

In particular, we need to program a repeater from Javascript, manipulating the search box, etc. We had some luck with the search box, but programming the state of drop-down menus (page size, etc.) has proved elusive.

Could you add documentation about this?

**Comment by interactivellama** [comment]
Please try the following:
http://getfuelux.com/javascript.html#repeater
http://getfuelux.com/extensions.html#bundled-extensions-list
http://getfuelux.com/extensions.html#bundled-extensions-thumbnail
http://fuelux-tutorials.herokuapp.com/repeater/

**Comment by vigna** [comment]
Of course we read carefully all those documents. NONE OF THEM provides the information required.

I want to call a JS function and have the filter drop-down list change from its current selected item to another one. Or call a JS function and have the number of items per page modified. The purpose is to modify the initial state of the repeater depending on the URL of the page, client-side

Can you point out exactly where this information would be in the documents above?

**Comment by interactivellama** [comment]
Apologies. I thought you were referring to programmatically interacting via the options object at initialization.

If you want to load the repeater into a specific page, I think that would be inside the datasource function. @kevinparkerson Do you have any feedback on going to page 10 at the initialization of repeater?

The dropdown menu is the `combobox` [control](http://getfuelux.com/javascript.html#combobox). You can look at how we used the search and sort-by boxes in [this prototype](http://fuelux-pages.herokuapp.com/overview/overview-basic/). That protoype makes use of [a small utilities library](http://www.fuelcdn.com/fuelux-utilities/1.0.0/js/fuelux-utilities.js) we made that's not been open-sourced but you find the file on the CDN under "Repeater Static DataSource."

You may have to make use of the `render` function with your datasource options passed in in order to manipulate the repeater content.

**Comment by vigna** [comment]
We ended up simulating the event:

                        $("#pageSize li[data-value=" + q.pageSize + "]").attr( "data-selected", "true" );
                        $("#pageSize li[data-value=" + q.pageSize + "] a").click();

It works.
