### ISSUE TITLE
Periodically refreshing Repeater causes flicker

### ISSUE THREAD

**Issue by robross0606** [ExactTarget/fuelux#1303]
Calling 'render' to refresh from a dynamic datasource causes the periodic flicker of a spinning render wheel.  This is cute, but should be optional.  The call is supposed to be a background call via AJAX and should seamlessly pop in the new data once the call is finished.  Preventing the the user from seeing existing data while new data is being pulled runs contrary to the AJAX concept.  Alternatively, provide another "refresh" function in addition to the current "render" function.

**Comment by kevinparkerson** [comment]
Hi @robross0606. Were you aware there is a `list_infiniteScroll` option that maintains previous data while new data is being loaded? Perhaps that can help solve your problem. Documentation can be found on [this page](http://getfuelux.com/extensions.html#bundled-extensions-list-options)

As for the default behavior, the design pattern we've followed calls for obvious indication that loading is occurring while new content is being pulled up; this means showing a loading icon, disabling the repeater search/filter/itemization/pagination/view controls, and clearing the repeater canvas of data. Since this is the design pattern our company needs we've crafted a [repeater extension API](http://getfuelux.com/extensions.html#writing-extensions-repeater) around this design, and unfortunately we can not change when the content is cleared without changing the expectations of that API.

**Comment by robross0606** [comment]
Isn't "obvious indication" a bit too heavy-handed for all use cases?  Why would you force users of your API to endure your interpretation of what they want to see?  What about simply having an optional callback a user can register to know when reloading is happening?  Allow users to decide if/when they want to give visual notification of reloads.  Half the purpose of AJAX is to do loading in the BACKGROUND.  Not wipe out the display the second a reload starts. It is both jarring and unnecessary, especially when refreshes are needed on a relatively frequent basis.

**Comment by robross0606** [comment]
At the very least, I would love to know the reasoning behind wiping out the view BEFORE the AJAX request has been made to pull the data.  Pull the data, render the data offscreen and THEN wipe the existing data and refresh.  Wiping the data before new data has been pulled negates the entire purpose of asynchronous requests.

**Comment by robross0606** [comment]
Do you have a good example for infinite scroll because I find the current documentation very confusing on that particular topic.
