### ISSUE TITLE
"selected.fu.repeaterList" and "deselected.fu.repeaterList" are not triggered from the API

### ISSUE THREAD

**Issue by robross0606** [ExactTarget/fuelux#1305]
These events don't trigger if the API is used to select or deselect items (list_setSelectedItems, list_clearSelectedItems, etc.)

**Comment by kevinparkerson** [comment]
Hi @robross0606. That is as-designed. Events such as those are only intended to fire if triggered by the user. This is a pattern followed for several controls within fuelux, and is done to avoid endless loops of triggering / event handling. The logic goes that if the code is calling the API to select or deselect items, the code is aware that this is occurring, and can call any functions afterwards that normally would be ran in response to an event. If there is a reason why this approach would not work for you, please let us know, otherwise we will close this issue soon. Thanks!

**Comment by robross0606** [comment]
Understood.  It wasn’t my expectation since I didn’t see that noted in the documentation.  However, I already refactored my code to do just that so I feel the only issue is lack of good notation in the documentation.  Unless it is there and I missed it.

**Comment by kevinparkerson** [comment]
I'm not sure it has been documented, so I've created an associated ticket to make sure that is covered somewhere. Thanks!
