### ISSUE TITLE
select list only displays selected item if items are wrapped in <a> tags, fails to raise selected event and fails to show mouse-over effect, doesn't support disabled items

### ISSUE THREAD

**Issue by robvon** [ExactTarget/fuelux#1308]
me thinks the  'li' items should be able to be just text.
Issues this causes:
The line items take on the styles for an 'a' tag (as you would expect) but I don't want this.
There is no mouse-over effect and no events
There is no support for a "disabled" line item

Also, there is an undocumented attribute "data-resize" used in the demos with no mention of possible values anywhere on the doco page. (other than "auto" - which still has no description)

Also, the selectlist supports both "click" and "changed" events. However the "click" event fires for both opening the control and clicking on an item. It can not detect a change although it fires on "text" only items. The "click" event is not documented...

btw - adding "fuelux" class to a container makes no difference. Is it only for certain components?

**Comment by interactivellama** [comment]
Philosophically, I agree. 

*The selectlist uses `a` because the basic [Bootstrap dropdown](http://getbootstrap.com/components/#btn-dropdowns-single) uses `a` tags
* Our library is declarative, you should be able to style the control as needed.
* I'll create and issue to document the `data-resize`.

None of the styles should take effect without a container "fuelux" class.

**Comment by cormacmccarthy** [comment]
We will be addressing this in an upcoming release. Thank you!
