### ISSUE TITLE
Scheduler Markup and Alignment

### ISSUE THREAD

**Issue by mbeard** [ExactTarget/fuelux#1511]
Adjust the scheduler markup for proper alignment.
<img width="966" alt="screenshot 2015-09-11 10 12 06" src="https://cloud.githubusercontent.com/assets/467352/9816893/c84e9178-586d-11e5-8ceb-ffbf779b4e9b.png">

- start date and end date fields should be the same width
- end date should be displayed inline and float to the right of the end selectlist (ie they shouldn't be in separate columns)

**Comment by scott-joe** [comment]
@cmcculloh does your new update to the Scheduler fix any of this?

**Comment by cmcculloh** [comment]
nope.

**Comment by scott-joe** [comment]
@cmcculloh okay cool

**Comment by scott-joe** [comment]
So, there's some oddness around the fact that some of these elements are fixed width and some are fluid width between start to end date and because of that oddness, they behave differently at smaller sizes...

Are you okay with this?
<img width="626" alt="screen shot 2015-10-08 at 1 30 37 pm" src="https://cloud.githubusercontent.com/assets/2026866/10374508/89eeb7fa-6dc1-11e5-9af0-251df942c5be.png">

**Comment by mbeard** [comment]
Yes, this looks much better!

**Comment by scott-joe** [comment]
MCTheme needs some fiddling so I'm going to get this wrapped up soon.

*Scott Williams*

*Sr. Front-End Engineer, UX Architecture*UXDS, Salesforce Marketing Cloud

**Comment by scott-joe** [comment]
https://github.com/ExactTarget/fuelux/pull/1563 submitted.
