### ISSUE TITLE
Tree open only one folder at a time

### ISSUE THREAD

**Issue by JacquesMarques** [ExactTarget/fuelux#1898]
When I click to open a folder I want the other open folders close, if its open.
How can I do this?

**Comment by cormacmccarthy** [comment]
Add an event listener to listen for `disclosedFolder.fu.tree` on the tree. Then try something like this (please note the following is completely 100% untested and was just written on the fly by me in the browser answering your question. use at your own risk):

```
    // Listen for branch open and attempt to close others
    $('#myTree').on('disclosedFolder.fu.tree', function closeOthers ($disclosedBranch) {
        // Loop through all open branches
        $('.tree-open').each(function closeBranch () {
            var $targetBranch = $(this);

            // Don't close the branch that was just disclosed
            if ($targetBranch.attr('id') !== $disclosedBranch.attr('id')) {
                var childWasDisclosed = false;
                // Make sure that none of it's children are the one that was just disclosed
                $targetBranch.find('.tree-open').each(function checkChildrenBranch () {
                    if ($(this).attr('id') === $disclosedBranch.attr('id')) {
                        childWasDisclosed = true;
                    }
                });

                if (!childWasDisclosed) {
                    $('#myTree').tree('closeBranch', $targetBranch);
                }
            }
        });
    });
```

**Comment by JacquesMarques** [comment]
@cormacmccarthy  I try your solution but when I open a folder it give-me an error:

TypeError: $disclosedBranch.attr is not a function

Can you help me with this?

**Comment by cormacmccarthy** [comment]
Take a look at the [docs](http://getfuelux.com/javascript.html#tree-usage-events). Specifically this line:
![image](https://user-images.githubusercontent.com/8006971/36434784-e254f88e-162d-11e8-8c7a-ff45b44f4958.png)

Judging by the docs, it looks like I was mistaken about the contents of `$disclosedBranch`. It does not appear (from the docs) that it will be a jQuery object set to the clicked DOM node, so I'd change that var to be called something like `disclosedBranchData`. Then either set a breakpoint or `console.log` out that var at the top of the `closeOthers` function (probably on the line that currently says `// Loop through all open branches`). What you're looking for is the `id` attr of the disclosed branch so that you can do a comparison in two places (like this `if ($targetBranch.attr('id') !== $disclosedBranch.attr('id')) {`). Probably instead of `$disclosedBranch.attr('id')` there you'll have to do something like `disclosedBranchData.id` or something. Hard to say without knowing exactly what that var contains (which you'll know from that console.log or the breakpoint).
