### ISSUE TITLE
Console error using checkbox

### ISSUE THREAD

**Issue by vernak2539** [ExactTarget/fuelux#2007]
## Description

I'm using the checkbox via the hbs template provided. On hover, via the `data-initialize`prop, it initialises itself. When it does this, I get an error in the error below in the console:

```
checkbox.js:41 Checkbox must be initialized on the `label` that wraps the `input` element. See https://github.com/ExactTarget/fuelux/blob/master/reference/markup/checkbox.html for example of proper markup. Call `.checkbox()` on the `<label>` not the `<input>`
```
Since I'm using the hbs template and it's initialised on hover, I have no idea why I'm getting this error. The markdown of the checkbox is below (again, generated by the hbs template provided).

![screen shot 2017-08-14 at 10 31 27](https://user-images.githubusercontent.com/521270/29266272-1ba7d198-80dc-11e7-9d85-99e2f47a90f1.png)

**Comment by vernak2539** [comment]
ping

**Comment by kcivey** [comment]
I believe the issue is that in the mouseover event handler `e.target` is the `span` tag, but `.checkbox()` needs to be called on the `label` tag. It seems to be a bug here, where `$(e.target)` (which is the element moused over, which could be a child of the label) should be `$(this)` (which is the label).
