### ISSUE TITLE
Use ISO 8601 in datepicker

### ISSUE THREAD

**Issue by vernak2539** [ExactTarget/fuelux#648]
Can we change the datepicker to use the [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601) for all functions including initializing the datepicker with a custom date, restricted dates, etc.? This would lead to less confusion, and then moment could parse it correctly based on culture

**Comment by swilliamset** [comment]
@vernak2539 documentation PR's are always welcome. Thanks for the heads up.

**Comment by interactivellama** [comment]
I've updated the documentation to speak to the use of formatting. http://getfuelux.com/javascript.html#datepicker-usage-moment

My understanding is that the same parsing and formatting is done at the input (API methods/options) as occurs for the output (`input` value), so unless one wants to output ISO 8601, at this moment :smile: at least, the API cannot take in an ISO8601 date format.

This has been frustrating for some developers (open source community and internal), since they expect the JavaScript controls to understand "machine-readable" ISO 8601.

**Comment by interactivellama** [comment]
I'm going to close this issue and open one to allow ISO 8601 formatted dates at inputs via the API.
