### ISSUE TITLE
Null/empty state for repeater?

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux#945]
There have been some requests for null/empty state for repeater. It would be similar to the no items found state. This would probably display some custom HTML. I'm not sure if the headers would still be present.

I think we could piggy back on the `*_noItemsHTML` option.

Requirements:
* move `*_noItemsHTML` to `*_noMatchingItemsHTML`
* `*_noMatchingItemsHTML` should be displayed if filter criteria is present but result list is 0
* `*_noItemsHTML` would be displayed when list is 0 and filter criteria not present
* support user story when visiting app for first time and creating first object

**Comment by mbeard** [comment]
Let's call the new property `_noMatchingRecordsHTML`.  If no items are found in the datasource, and at least one filter related option has been supplied (filter, page, search, etc.), then this property would be used.  If no filter-related option has been supplied, it would use `_noItemsHTML`.  Thoughts?

**Comment by kevinparkerson** [comment]
I'm having a hard time understanding the difference. A common setting for noItemsHTML is this: `list_noItemsHTML: 'no items found'`  That would work for any situation in which no items were returned from the datasource. Are you saying you want more specific items based on which dataSourceOptions were provided? If so, we'd need the plugins to also have access to those options - which is currently not the case. Adding that would not be an enormous issue though thankfully due to the fact that each plugin function is passed a `helpers` object as an argument, so the dataSourceOptions can be attached to that.

**Comment by mbeard** [comment]
One of the main differences might be around first time user experience.  If it's the user's first time in a product, they wouldn't have created anything yet and would see "no items".  However, in this scenario, we like want to show a different call to action like "click create to get started...".  This message would be different though for a user that searching against and existing dataset, but no results were found based on their criteria.

**Comment by swilliamset** [comment]
Added list of requirements to original description

**Comment by swilliamset** [comment]
@interactivellama can this be closed with Issue#1436 and PR#1437

**Comment by cormacmccarthy** [comment]
Does this apply to empty filterset?

**Comment by mbeard** [comment]
I believe this is specific to an error state and doesn't account for null or empty states (note: these are 2 distinct states).  I believe this is still needed.
